### ISSUE TITLE
No such file or directory error encountered

### ISSUE THREAD

**Issue by navuboy** [afruehstueck/tileGAN#12]
Hi i tried to setup yor environment on my local pc and encountering the following error, what should be the issue?

![Screenshot from 2022-10-18 16-14-14](https://user-images.githubusercontent.com/33291299/196455884-8460e582-51e0-4033-8a06-025fff53b842.png)

**Comment by afruehstueck** [comment]
Your error looks like you have trouble with cuda (hence the `Could not load dynamic library 'libcudart.so.11.0' [...]` error). I would suggest you review your dependency imports!

**Comment by navuboy** [comment]
The issue was with my cuda toolkit installation, sorted now. But I am encountering another import error issue:, how to resolve this? 
![Screenshot from 2022-10-20 09-37-43](https://user-images.githubusercontent.com/33291299/196886305-1207ef07-391e-4c72-bc07-14f2ebcc9311.png)

**Comment by afruehstueck** [comment]
Did you follow the instructions to install hnswlib?
```
git clone https://github.com/nmslib/hnswlib.git
cd hnswlib/python_bindings
python setup.py install
```
I'm pretty sure your hnswlib was not compiled correctly in the last step.

**Comment by navuboy** [comment]
Yes I installed the hnswlib again after sorting the dependencies issue, still encountering the import error :(
BTW, should i clone the hnswlib repo within the tileGAN repo? or is there any specific version for it?

**Comment by navuboy** [comment]
issue resolved, thanks
