### ISSUE TITLE
tensorflow.python .framework error

### ISSUE THREAD

**Issue by navuboy** [afruehstueck/tileGAN#14]
Hi, I'm encountering the following error related to GPU/CPU ID allocation whenever I am trying to execute any option on the GUI, is there any command to enable cuda specifcally? 
![Screenshot from 2022-10-20 14-39-59](https://user-images.githubusercontent.com/33291299/196951435-f0bf0142-e510-4ddf-9383-27b7de1788da.png)

I was able to launch the GUI but not able to enlarge the imageand how to remove the tutorial option from the GUI?
![Screenshot from 2022-10-20 14-44-17](https://user-images.githubusercontent.com/33291299/196952155-c27e2068-2158-41c9-99c3-abc4c6f751d3.png)

**Comment by afruehstueck** [comment]
Re (1): Do you have a CUDA-capable GPU in your device? I have never tried to run the tool without GPU, I don't think this will work. If you do, then there is another problem with loading CUDA. Tensorflow is a huge pain with getting everything set up correctly.
Re (2): The tutorial is always loaded as the splash screen, as described on the tutorial page, you proceed to generate an output by randomizing a grid or loading an image.

**Comment by navuboy** [comment]
I am currently using CUDA capable GPU - CUDA 11.5 to be precise, but I guess it's some sot of a dependency issue with Tensorflow. I am facing this issue now with the gpu id not being detected in the client channel, whenever i try to select any option on the GUI.
![Screenshot from 2022-10-20 17-22-07](https://user-images.githubusercontent.com/33291299/196990656-5249b841-ae4d-4a25-a0d2-b3b6525ca1b2.png)
