### ISSUE TITLE
Creating custom dataset from stylegan2-ada trained models

### ISSUE THREAD

**Issue by navuboy** [afruehstueck/tileGAN#16]
Hi, 
will I be able to create a custom dataset from a stylegan2-ada trained model? I have the training results (from the stylegan2-ada) are saved as .pkl files.

**Comment by afruehstueck** [comment]
Are you talking about the Tensorflow version of StyleGAN2-ADA? You would need to make some changes to the tileGAN code, because the network architecture is quite different. It is doable, we had some preliminary results for tileGAN on StyleGAN, but they are not compatible with this codebase.
