### ISSUE TITLE
using Progressive Growing of GANs for too long training time

### ISSUE THREAD

**Issue by Yongzhang-Tan** [afruehstueck/tileGAN#18]
Hello author, I hope to synthesize a dozen input map images, but training using Progressive Growing of GANs takes a very long time. Is there any model that can train such small sample data and obtain a network quickly?

**Comment by afruehstueck** [comment]
Sounds like a fine-tuning job. I haven't tried this personally for this particular project, but you could take an existing trained model and fine-tune it for a small number of iterations on your own data.
