### ISSUE TITLE
Landscape Dataset Availability

### ISSUE THREAD

**Issue by egershenfeld** [afruehstueck/tileGAN#2]
This project is wonderful, and I can't wait to get it running on my computer.

Is there any chance the trained network for the landscape generation will become available? The results from it are super impressive and I would love to play around with it.

Thanks!

**Comment by afruehstueck** [comment]
Thanks for the kind words and for your interest in this project! Please contact us by email to discuss any data and/or code concerns and questions you might be having.

**Comment by ddesmond** [comment]
I am also interested in experimenting with said dataset. Cant find any contact email. How can i reach you?
Thanks!

**Comment by afruehstueck** [comment]
Oh, sorry! My email is anna.fruehstueck (at) kaust.edu.sa
