### ISSUE TITLE
PySide2/Qt python / module versions?

### ISSUE THREAD

**Issue by MrDavidYu** [afruehstueck/tileGAN#3]
I'm running into a lot of issues with module dependencies when I try to run tileGAN_client.py, for e.g. 
from PySide2 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed: The specified module could not be found.

I suspect it might have something to do with my python / module versioning. Could you provide a list of module versions that worked and also what systems you tried this on?

Thanks

**Comment by afruehstueck** [comment]
Hi @jakubLangr, sorry to hear you have issues with the dependencies. Can you clarify which of the two described problems you're having? 
The Qt problem is a bit tricky, and I've been repeatedly running into it when working with Qt. I'm usually running TileGAN on a Linux server and a Windows 10 client. 

You could try the following approaches:

- Copy the Qt dlls from:
```
\Anaconda3\Lib\site-packages\PySide2\plugins\platforms\qminimal.dll
\Anaconda3\Lib\site-packages\PySide2\plugins\platforms\qoffscreen.dll
\Anaconda3\Lib\site-packages\PySide2\plugins\platforms\qwindows.dll
```
to
```\Anaconda3\Library\plugins\platforms\```

- Alternatively, you could try to explicity (re-)specify the Qt path in the first line of code:
```
import os
import PySide2

dirname = os.path.dirname(PySide2.__file__)
plugin_path = os.path.join(dirname, 'plugins', 'platforms')
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = plugin_path
```
