### ISSUE TITLE
PySide2 DLL load failed

### ISSUE THREAD

**Issue by powerspowers** [afruehstueck/tileGAN#6]
Any advice on what might not be loading? The error message is none too helpful. I installed qt and pyside2 using conda.

>python tileGAN_client.py localhost
Traceback (most recent call last):
  File "tileGAN_client.py", line 1, in <module>
    from PySide2 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed: The specified module could not be found.

**Comment by afruehstueck** [comment]
Which Python version are you running in your environment? Some possible complications are described [here](https://wiki.qt.io/Qt_for_Python/Considerations#Missing_DLLs_on_Windows).

**Comment by powerspowers** [comment]
Python 3.7.4

if I run 'python -v -c "import PySide2" this loads. When I try to import QtCore or any other subset from PySide2 then I get the DLL failure.

I'm not sure what it means to 'update your virtualenv package' 

I activated anaconda

**Comment by afruehstueck** [comment]
Maybe try updating your conda? `conda update --all`
This message seems a bit cryptic.

**Comment by powerspowers** [comment]
Thanks. Updated and have the same DLL issue ... will keep hunting. Seems like there are a few posts I found that show the same problem of being able to load PySide2 but not QtCore etc ... noone posted a good solution though.

Seems like something with the python runtime

**Comment by afruehstueck** [comment]
Another option would be to uninstall PySide2 from conda and try installing using pip. 
It seems this guy had the same issue: https://github.com/afruehstueck/tileGAN/issues/3

**Comment by powerspowers** [comment]
That's exactly what I did. Uninstall in conda and then installed with pip. That seems to work!

Now I have a Qt plugin problem. Sounds like some kind of WIndows specific driver has to be connected for Qt to work on windows. Probably need direct2D is my guess … looking ...

Attempting to connect to TensorFlow manager at localhost:8080...
Connected to server!
qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: direct2d, minimal, offscreen, windows.

**Comment by afruehstueck** [comment]
This one is familiar. You should be able to fix it by copying some dlls, I described that [here](https://github.com/afruehstueck/tileGAN/issues/3#issuecomment-531553730).

**Comment by powerspowers** [comment]
Bingo, that's what worked. Now I have the client GUI up and running … time to figure out how to create an image!!!

Thank you SO much.
