### ISSUE TITLE
Save file not working

### ISSUE THREAD

**Issue by powerspowers** [afruehstueck/tileGAN#8]
Created a 25x75 tile from the suerat model. When I attempt to save the image the file does not appear. 

Output in the client console says:
('D:/tilesamples/seurat1.jpg', 'All Files (*)')
('D:/tilesamples/seurat1', 'All Files (*)')

**Comment by afruehstueck** [comment]
This is weird. Some of the user interaction in TileGAN is a bit wonky, but saving should work reliably. You do need to specify the file extension in the saving dialogue.

![tilegan_saving](https://user-images.githubusercontent.com/19155913/74328957-ec6e1e80-4d9f-11ea-862f-14430f94625d.gif)

**Comment by powerspowers** [comment]
I'm not getting the behavior where I can place a tile in a spot and have it fill in. I get an index error instead. Wonder if its because I'm on TF 1.5 rather than 1.8

I tried .jpg and .png for saving and it doesn't result in a file. No output
